Repository Requisitos-de-Software/2023.2-e-Titulo, pull requests merged in 2023-11, with the labels that each got.

#58 Feature ata reuniao 10
  docs/atas/ata_reuniao_10.md
Labels: documentation

#60 Feature apresentacao04
  docs/apresentacoes/apresentacao04.md
Labels: apresentação

#61 Feature ata reuniao 11
  docs/atas/ata_reuniao_01.md
  docs/atas/ata_reuniao_02.md
  docs/atas/ata_reuniao_10.md
  docs/atas/ata_reuniao_11.md
Labels: documentation

#73 Feature verificacao mariiana
  docs/planejamento/aplicativoescolhido.md
  docs/verificacao/verificacaoGrupo+1/etapa1/PlanejamentoVerificacaoEtapa1.md
  docs/verificacao/verificacaoGrupo+1/etapa1/richPicture.md
  docs/verificacao/verificacaoGrupo+1/etapa2/MoSCoW.md
  docs/verificacao/verificacaoGrupo+1/etapa2/PlanejamentoVerificacaoEtapa2.md
  docs/verificacao/verificacaoGrupo+1/etapa2/TLS.md
  docs/verificacao/verificacaoGrupo+1/etapa4/PlanejamentoVerificacaoEtapa4.md
  docs/verificacao/verificacaoGrupo+1/etapa4/backlog.md
Labels: documentation, apresentação

#81 Feature backward
  docs/elicitacao/tecnicas/entrevista.md
  docs/elicitacao/tecnicas/introspeccao.md
  docs/elicitacao/tecnicas/questionario.md
  docs/elicitacao/tecnicas/storytelling.md
  docs/modelagem/agil/backlog.md
  docs/pos-rastreabilidade/backward-from.md
  docs/pos-rastreabilidade/backwardFrom.md
Labels: documentation, apresentação

#82 [UPDATE] cronograma executado entrega 5.1 e entrega 6
  docs/planejamento/CronogramaExecutado.md
Labels: documentation

#92 Feature verificacao mariiana
  docs/verificacao/verificacaoGrupo+1/etapa1/PlanejamentoVerificacaoEtapa1.md
  docs/verificacao/verificacaoGrupo+1/etapa1/richPicture.md
  docs/verificacao/verificacaoGrupo+1/etapa2/MoSCoW.md
  docs/verificacao/verificacaoGrupo+1/etapa2/PlanejamentoVerificacaoEtapa2.md
  docs/verificacao/verificacaoGrupo+1/etapa2/TLS.md
  docs/verificacao/verificacaoGrupo+1/etapa4/PlanejamentoVerificacaoEtapa4.md
  docs/verificacao/verificacaoGrupo+1/etapa4/backlog.md
  docs/verificacao/verificacaoGrupo4/etapa2/PlanejamentoVerificacaoEtapa2.md
  docs/verificacao/verificacaoGrupo4/etapa2/brainstorming.md
  docs/verificacao/verificacaoGrupo4/etapa2/questionario.md
  docs/verificacao/verificacaoGrupo4/etapa4/PlanejamentoVerificacaoEtapa4.md
  docs/verificacao/verificacaoGrupo4/etapa4/historiasUsuario.md
  docs/verificacao/verificacaoGrupo4/etapa4/nfrFramework.md
Labels: documentation
